// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using login.Models;

#nullable disable

namespace flutterApi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231119101556_EditMedicalPricingData3")]
    partial class EditMedicalPricingData3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarUser", b =>
                {
                    b.Property<int>("CarsCarId")
                        .HasColumnType("int");

                    b.Property<string>("usersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CarsCarId", "usersId");

                    b.HasIndex("usersId");

                    b.ToTable("CarUser");
                });

            modelBuilder.Entity("flutterApi.Models.Accident", b =>
                {
                    b.Property<int>("AccidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccidentId"), 1L, 1);

                    b.Property<string>("AccidentLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccidentId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("Accidents");
                });

            modelBuilder.Entity("flutterApi.Models.AgeLimits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<int>("MedicalCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCompanyId");

                    b.ToTable("ageLimits");
                });

            modelBuilder.Entity("flutterApi.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarPrice")
                        .HasColumnType("int");

                    b.Property<string>("ManufacturingYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("flutterApi.Models.CarInfo", b =>
                {
                    b.Property<int>("CarInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarInfoId"), 1L, 1);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarInfoId");

                    b.ToTable("carInfo");
                });

            modelBuilder.Entity("flutterApi.Models.CarModel", b =>
                {
                    b.Property<int>("CarModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarModelId"), 1L, 1);

                    b.Property<int?>("CarInfoId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarModelId");

                    b.HasIndex("CarInfoId");

                    b.ToTable("carModels");
                });

            modelBuilder.Entity("flutterApi.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"), 1L, 1);

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("flutterApi.Models.CompanyBenfits", b =>
                {
                    b.Property<int>("CompanyBenfitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyBenfitsId"), 1L, 1);

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int");

                    b.Property<string>("benfit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyBenfitsId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("companyBenfits");
                });

            modelBuilder.Entity("flutterApi.Models.CompanyHealthInsuranceTypes", b =>
                {
                    b.Property<int>("CompanyHealthInsuranceTypesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyHealthInsuranceTypesId"), 1L, 1);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("MedicalCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyHealthInsuranceTypesId");

                    b.HasIndex("MedicalCompanyId");

                    b.ToTable("compsnyHealthInsuranceTypes");
                });

            modelBuilder.Entity("flutterApi.Models.CompanyInfo", b =>
                {
                    b.Property<int>("CompanyInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyInfoId"), 1L, 1);

                    b.Property<int?>("CarModelId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("CompanyInfoId");

                    b.HasIndex("CarModelId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyInfo");
                });

            modelBuilder.Entity("flutterApi.Models.HomeCompany", b =>
                {
                    b.Property<int>("HomeCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeCompanyId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyName")
                        .HasColumnType("int");

                    b.HasKey("HomeCompanyId");

                    b.ToTable("HomeCompany");
                });

            modelBuilder.Entity("flutterApi.Models.HomeLimits", b =>
                {
                    b.Property<int>("HomeLimitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeLimitsId"), 1L, 1);

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<int>("HomeCompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("NetPremium")
                        .HasColumnType("int");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.Property<int>("TotalInstallment")
                        .HasColumnType("int");

                    b.HasKey("HomeLimitsId");

                    b.HasIndex("HomeCompanyId");

                    b.ToTable("homeLimits");
                });

            modelBuilder.Entity("flutterApi.Models.HomePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HomeCompanyId")
                        .HasColumnType("int");

                    b.Property<double?>("PriceOfBuildings")
                        .HasColumnType("float");

                    b.Property<double?>("PriceOfTheContentOfBuilding")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HomeCompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("homePrices");
                });

            modelBuilder.Entity("flutterApi.Models.ImageAccidentDB", b =>
                {
                    b.Property<int>("ImageAccidentDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageAccidentDBId"), 1L, 1);

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("ImageAccidentDBId");

                    b.ToTable("ImageDB");
                });

            modelBuilder.Entity("flutterApi.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Classificatin")
                        .HasColumnType("int");

                    b.Property<int>("CompanyInfoId")
                        .HasColumnType("int");

                    b.Property<string>("ConsumptionRatios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliceReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saviors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("insurancePrice")
                        .HasColumnType("real");

                    b.Property<string>("insuranceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInfoId");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("flutterApi.Models.InsuranceRequest", b =>
                {
                    b.Property<int>("InsuranceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceRequestId"), 1L, 1);

                    b.Property<bool?>("Accepted")
                        .HasColumnType("bit");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyInsuranceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NeedPreviewer")
                        .HasColumnType("bit");

                    b.Property<string>("Premium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("carPrice")
                        .HasColumnType("int");

                    b.HasKey("InsuranceRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("insuranceRequests");
                });

            modelBuilder.Entity("flutterApi.Models.MedicalCompany", b =>
                {
                    b.Property<int>("MedicalCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalCompanyId"), 1L, 1);

                    b.Property<int>("CompanyName")
                        .HasColumnType("int");

                    b.HasKey("MedicalCompanyId");

                    b.ToTable("medicalCompanies");
                });

            modelBuilder.Entity("flutterApi.Models.MedicalInsurancePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgeLimitsId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyHealthInsuranceTypesId")
                        .HasColumnType("int");

                    b.Property<float>("Premium")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AgeLimitsId");

                    b.HasIndex("CompanyHealthInsuranceTypesId");

                    b.ToTable("medicalInsurancePrices");
                });

            modelBuilder.Entity("flutterApi.Models.MedicalPricingData", b =>
                {
                    b.Property<int>("MedicalPricingDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalPricingDataId"), 1L, 1);

                    b.Property<int>("CompanyHealthInsuranceTypesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicalCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MedicalPricingDataId");

                    b.HasIndex("CompanyHealthInsuranceTypesId");

                    b.HasIndex("MedicalCompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("medicalPricingsData");
                });

            modelBuilder.Entity("flutterApi.Models.PersonalAccidentCompany", b =>
                {
                    b.Property<int>("PersonalAccidentCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalAccidentCompanyId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyName")
                        .HasColumnType("int");

                    b.HasKey("PersonalAccidentCompanyId");

                    b.ToTable("PersonalAccidentCompanies");
                });

            modelBuilder.Entity("flutterApi.Models.PersonalAccidentLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<int?>("NetPremium")
                        .HasColumnType("int");

                    b.Property<int>("PersonalAccidentCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.Property<int>("TotalInstallment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalAccidentCompanyId");

                    b.ToTable("PersonalAccidentLimit");
                });

            modelBuilder.Entity("flutterApi.Models.PersonalAccidentPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PersonalAccidentCompanyId")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalAccidentCompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalAccidentPrice");
                });

            modelBuilder.Entity("flutterApi.Models.PersonalImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("CarLicense")
                        .IsRequired()
                        .HasColumnType("image");

                    b.Property<byte[]>("Idcard")
                        .IsRequired()
                        .HasColumnType("image")
                        .HasColumnName("IDCard");

                    b.Property<byte[]>("PersonalDrivingLicense")
                        .IsRequired()
                        .HasColumnType("image");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalImages");
                });

            modelBuilder.Entity("flutterApi.Models.PersonalImagesDB", b =>
                {
                    b.Property<int>("PersonalImagesDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalImagesDBId"), 1L, 1);

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalImagesDBId");

                    b.ToTable("personalImagesDB");
                });

            modelBuilder.Entity("flutterApi.Models.personalImagesUrl", b =>
                {
                    b.Property<int>("personalImagesUrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personalImagesUrlId"), 1L, 1);

                    b.Property<string>("CarLicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalDrivingLicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("personalImagesUrlId");

                    b.HasIndex("UserId");

                    b.ToTable("personalImagesUrls");
                });

            modelBuilder.Entity("flutterApi.Models.PlaceOfTreatment", b =>
                {
                    b.Property<int>("PlaceOfTreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceOfTreatmentId"), 1L, 1);

                    b.Property<int>("MedicalCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaceOfTreatmentId");

                    b.HasIndex("MedicalCompanyId");

                    b.ToTable("placeOfTreatments");
                });

            modelBuilder.Entity("flutterApi.Models.PlaceOfTreatmentDetails", b =>
                {
                    b.Property<int>("PlaceOfTreatmentDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceOfTreatmentDetailsId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceOfTreatmentId")
                        .HasColumnType("int");

                    b.HasKey("PlaceOfTreatmentDetailsId");

                    b.HasIndex("PlaceOfTreatmentId");

                    b.ToTable("PlaceOfTreatmentDetails");
                });

            modelBuilder.Entity("flutterApi.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"), 1L, 1);

                    b.Property<int>("GrossPremium")
                        .HasColumnType("int");

                    b.Property<int>("NetPremium")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SumInsurance")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("policyNumber")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("policies");
                });

            modelBuilder.Entity("flutterApi.Models.PreviewerReport", b =>
                {
                    b.Property<int>("PreviewerReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreviewerReportId"), 1L, 1);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Report")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PreviewerReportId");

                    b.HasIndex("UserId");

                    b.ToTable("previewerReports");
                });

            modelBuilder.Entity("flutterApi.Models.PriceOffers", b =>
                {
                    b.Property<int>("PriceOffersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceOffersId"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OfferPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PriceOffersId");

                    b.HasIndex("CarId");

                    b.ToTable("PriceOffers");
                });

            modelBuilder.Entity("flutterApi.Models.ReportImageDb", b =>
                {
                    b.Property<int>("ReportImageDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportImageDbId"), 1L, 1);

                    b.Property<string>("ReportImageDbName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportImageDbPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportImageDbId");

                    b.ToTable("reportImageDb");
                });

            modelBuilder.Entity("flutterApi.Models.typesMedicalDetails", b =>
                {
                    b.Property<int>("CompanyHealthInsuranceTypesId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceOfTreatmentDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyHealthInsuranceTypesId", "PlaceOfTreatmentDetailsId");

                    b.HasIndex("PlaceOfTreatmentDetailsId");

                    b.ToTable("typesMedicalDetails");
                });

            modelBuilder.Entity("flutterApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RegWay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("CarUser", b =>
                {
                    b.HasOne("flutterApi.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("CarsCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flutterApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("usersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("flutterApi.Models.Accident", b =>
                {
                    b.HasOne("flutterApi.Models.Policy", "policy")
                        .WithMany("Accidents")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flutterApi.Models.User", "user")
                        .WithMany("Accidents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("policy");

                    b.Navigation("user");
                });

            modelBuilder.Entity("flutterApi.Models.AgeLimits", b =>
                {
                    b.HasOne("flutterApi.Models.MedicalCompany", "MedicalCompany")
                        .WithMany()
                        .HasForeignKey("MedicalCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCompany");
                });

            modelBuilder.Entity("flutterApi.Models.CarModel", b =>
                {
                    b.HasOne("flutterApi.Models.CarInfo", null)
                        .WithMany("carModels")
                        .HasForeignKey("CarInfoId");
                });

            modelBuilder.Entity("flutterApi.Models.CompanyBenfits", b =>
                {
                    b.HasOne("flutterApi.Models.Insurance", null)
                        .WithMany("Benfits")
                        .HasForeignKey("InsuranceId");
                });

            modelBuilder.Entity("flutterApi.Models.CompanyHealthInsuranceTypes", b =>
                {
                    b.HasOne("flutterApi.Models.MedicalCompany", "MedicalCompany")
                        .WithMany("Types")
                        .HasForeignKey("MedicalCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCompany");
                });

            modelBuilder.Entity("flutterApi.Models.CompanyInfo", b =>
                {
                    b.HasOne("flutterApi.Models.CarModel", "CarModel")
                        .WithMany("CompanyInfo")
                        .HasForeignKey("CarModelId");

                    b.HasOne("flutterApi.Models.Company", "Company")
                        .WithMany("CompanyInfos")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("flutterApi.Models.HomeLimits", b =>
                {
                    b.HasOne("flutterApi.Models.HomeCompany", "HomeCompany")
                        .WithMany()
                        .HasForeignKey("HomeCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeCompany");
                });

            modelBuilder.Entity("flutterApi.Models.HomePrice", b =>
                {
                    b.HasOne("flutterApi.Models.HomeCompany", "HomeCompany")
                        .WithMany("PriceList")
                        .HasForeignKey("HomeCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flutterApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("flutterApi.Models.Insurance", b =>
                {
                    b.HasOne("flutterApi.Models.CompanyInfo", "CompanyInfo")
                        .WithMany("insurance")
                        .HasForeignKey("CompanyInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyInfo");
                });

            modelBuilder.Entity("flutterApi.Models.InsuranceRequest", b =>
                {
                    b.HasOne("flutterApi.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("flutterApi.Models.MedicalInsurancePrice", b =>
                {
                    b.HasOne("flutterApi.Models.AgeLimits", "AgeLimits")
                        .WithMany()
                        .HasForeignKey("AgeLimitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flutterApi.Models.CompanyHealthInsuranceTypes", "CompanyHealthInsuranceTypes")
                        .WithMany()
                        .HasForeignKey("CompanyHealthInsuranceTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeLimits");

                    b.Navigation("CompanyHealthInsuranceTypes");
                });

            modelBuilder.Entity("flutterApi.Models.MedicalPricingData", b =>
                {
                    b.HasOne("flutterApi.Models.CompanyHealthInsuranceTypes", "insuranceTypes")
                        .WithMany()
                        .HasForeignKey("CompanyHealthInsuranceTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flutterApi.Models.MedicalCompany", "MedicalCompany")
                        .WithMany("PricingData")
                        .HasForeignKey("MedicalCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flutterApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCompany");

                    b.Navigation("User");

                    b.Navigation("insuranceTypes");
                });

            modelBuilder.Entity("flutterApi.Models.PersonalAccidentLimit", b =>
                {
                    b.HasOne("flutterApi.Models.PersonalAccidentCompany", "MedicalCompany")
                        .WithMany()
                        .HasForeignKey("PersonalAccidentCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCompany");
                });

            modelBuilder.Entity("flutterApi.Models.PersonalAccidentPrice", b =>
                {
                    b.HasOne("flutterApi.Models.PersonalAccidentCompany", "HomeCompany")
                        .WithMany()
                        .HasForeignKey("PersonalAccidentCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flutterApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("flutterApi.Models.PersonalImage", b =>
                {
                    b.HasOne("flutterApi.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("flutterApi.Models.personalImagesUrl", b =>
                {
                    b.HasOne("flutterApi.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("flutterApi.Models.PlaceOfTreatment", b =>
                {
                    b.HasOne("flutterApi.Models.MedicalCompany", "MedicalCompany")
                        .WithMany("Treatments")
                        .HasForeignKey("MedicalCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCompany");
                });

            modelBuilder.Entity("flutterApi.Models.PlaceOfTreatmentDetails", b =>
                {
                    b.HasOne("flutterApi.Models.PlaceOfTreatment", "PlaceOfTreatment")
                        .WithMany()
                        .HasForeignKey("PlaceOfTreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaceOfTreatment");
                });

            modelBuilder.Entity("flutterApi.Models.Policy", b =>
                {
                    b.HasOne("flutterApi.Models.User", "Users")
                        .WithMany("Policies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("flutterApi.Models.PreviewerReport", b =>
                {
                    b.HasOne("flutterApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("flutterApi.Models.PriceOffers", b =>
                {
                    b.HasOne("flutterApi.Models.Car", "Car")
                        .WithMany("PriceOffers")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("flutterApi.Models.typesMedicalDetails", b =>
                {
                    b.HasOne("flutterApi.Models.CompanyHealthInsuranceTypes", "CompanyHealthInsuranceTypes")
                        .WithMany("typesMedicalDetails")
                        .HasForeignKey("CompanyHealthInsuranceTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flutterApi.Models.PlaceOfTreatmentDetails", "PlaceOfTreatmentDetails")
                        .WithMany("typesMedicalDetails")
                        .HasForeignKey("PlaceOfTreatmentDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyHealthInsuranceTypes");

                    b.Navigation("PlaceOfTreatmentDetails");
                });

            modelBuilder.Entity("flutterApi.Models.User", b =>
                {
                    b.OwnsMany("flutterApi.Models.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("flutterApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("flutterApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flutterApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("flutterApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("flutterApi.Models.Car", b =>
                {
                    b.Navigation("PriceOffers");
                });

            modelBuilder.Entity("flutterApi.Models.CarInfo", b =>
                {
                    b.Navigation("carModels");
                });

            modelBuilder.Entity("flutterApi.Models.CarModel", b =>
                {
                    b.Navigation("CompanyInfo");
                });

            modelBuilder.Entity("flutterApi.Models.Company", b =>
                {
                    b.Navigation("CompanyInfos");
                });

            modelBuilder.Entity("flutterApi.Models.CompanyHealthInsuranceTypes", b =>
                {
                    b.Navigation("typesMedicalDetails");
                });

            modelBuilder.Entity("flutterApi.Models.CompanyInfo", b =>
                {
                    b.Navigation("insurance");
                });

            modelBuilder.Entity("flutterApi.Models.HomeCompany", b =>
                {
                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("flutterApi.Models.Insurance", b =>
                {
                    b.Navigation("Benfits");
                });

            modelBuilder.Entity("flutterApi.Models.MedicalCompany", b =>
                {
                    b.Navigation("PricingData");

                    b.Navigation("Treatments");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("flutterApi.Models.PlaceOfTreatmentDetails", b =>
                {
                    b.Navigation("typesMedicalDetails");
                });

            modelBuilder.Entity("flutterApi.Models.Policy", b =>
                {
                    b.Navigation("Accidents");
                });

            modelBuilder.Entity("flutterApi.Models.User", b =>
                {
                    b.Navigation("Accidents");

                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
